namespace CityCommunicationCenter.Shared.Contracts;

public sealed record MailNotificationSettingsResponse(
    bool IsEnabled,
    bool SmtpHostSpecified,
    string? SmtpHost,
    bool PortSpecified,
    int Port,
    bool AuthenticationEnabled,
    string? Username,
    bool HasPassword,
    string SecurityMode,
    string? DefaultReplyTo,
    bool IncomingMailEnabled = false,
    string IncomingSubjectTemplate = "{TalepNo}",
    string IncomingBodyTemplate = "{TalepNo}",
    bool ExcludedUsersEnabled = false,
    IReadOnlyList<Guid>? ExcludedUserIds = null,
    bool OverdueMailEnabled = false,
    string OverdueSubjectTemplate = "{TalepNo}",
    string OverdueBodyTemplate = "{TalepNo}",
    bool OverdueTaskMailEnabled = false,
    string OverdueTaskSubjectTemplate = "{GörevNo}",
    string OverdueTaskBodyTemplate = "{GörevNo} no'lu {GörevBaşlığı}",
    bool AssignmentMailEnabled = false,
    string AssignmentSubjectTemplate = "{GörevNo}",
    string AssignmentBodyTemplate = "{GörevNo} no'lu {GörevBaşlığı}");

public sealed record UpdateMailNotificationSettingsRequest(
    bool IsEnabled,
    bool SmtpHostSpecified,
    string? SmtpHost,
    bool PortSpecified,
    int Port,
    bool AuthenticationEnabled,
    string? Username,
    string? Password,
    bool ClearPassword,
    string SecurityMode,
    string? DefaultReplyTo,
    bool? IncomingMailEnabled = null,
    string? IncomingSubjectTemplate = null,
    string? IncomingBodyTemplate = null,
    bool? ExcludedUsersEnabled = null,
    IReadOnlyList<Guid>? ExcludedUserIds = null,
    bool? OverdueMailEnabled = null,
    string? OverdueSubjectTemplate = null,
    string? OverdueBodyTemplate = null,
    bool? OverdueTaskMailEnabled = null,
    string? OverdueTaskSubjectTemplate = null,
    string? OverdueTaskBodyTemplate = null,
    bool? AssignmentMailEnabled = null,
    string? AssignmentSubjectTemplate = null,
    string? AssignmentBodyTemplate = null);

public sealed record TestMailRequest(
    string? SmtpHost,
    int Port,
    bool AuthenticationEnabled,
    string? Username,
    string? Password,
    string SecurityMode,
    string? DefaultReplyTo,
    string? RecipientEmail);

public sealed record TestMailResponse(bool Success, string Message);
