// <auto-generated />
using System;
using CityCommunicationCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityCommunicationCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CityCommunicationCenterDbContext))]
    partial class CityCommunicationCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("AdditionalRoleCodesJson")
                        .HasColumnType("text")
                        .HasColumnName("additionalrolecodesjson");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalIdentityId")
                        .HasColumnType("text")
                        .HasColumnName("externalidentityid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manageruserid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rolecode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<string>("UserSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usersource");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId", "Email");

                    b.HasIndex("TenantId", "RoleCode");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenantid_username_unique")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("6d146a0d-611c-48a5-b59e-8c14a22f6a2e"),
                            DisplayName = "Sistem Yöneticisi",
                            Email = "admin@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "SystemAdmin",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            DisplayName = "Zeynep Kara",
                            Email = "zeynep.kara@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "Manager",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "zeynep.kara"
                        },
                        new
                        {
                            UserId = new Guid("1358d4aa-b1ae-486c-a1db-a757ea18f2c3"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            DisplayName = "Emre Çelik",
                            Email = "emre.celik@tire.bel.tr",
                            IsActive = true,
                            ManagerUserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            RoleCode = "Staff",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "emre.celik"
                        },
                        new
                        {
                            UserId = new Guid("1e96916a-889a-4701-a0e6-71dc6571ac18"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("8f7264ff-c1df-48eb-bf39-a6ff42d7e9bc"),
                            DisplayName = "Ali Yıldız",
                            Email = "ali.yildiz@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "Operator",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "ali.yildiz"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AssignmentHistory", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<DateTimeOffset>("ActionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actiondateutc");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actiontype");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid?>("FromDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fromdepartmentid");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("fromuserid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<Guid?>("ToDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("todepartmentid");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("touserid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("TaskId", "ActionDateUtc");

                    b.HasIndex("TenantId", "ToDepartmentId");

                    b.ToTable("assignmenthistory", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attachmentid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenttype");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entitytype");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("filesizebytes");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relativeurl");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storedfilename");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("AttachmentId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("auditlogid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("actordisplayname");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actoruserid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("departmentname");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entitytype");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eventtimeutc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("StatusAtEvent")
                        .HasColumnType("text")
                        .HasColumnName("statusatevent");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("AuditLogId");

                    b.HasIndex("TenantId", "EventTimeUtc");

                    b.HasIndex("TenantId", "EntityType", "EntityId");

                    b.ToTable("auditlogs", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.CitizenConversation", b =>
                {
                    b.Property<Guid>("CitizenConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("citizenconversationid");

                    b.Property<string>("CitizenName")
                        .HasColumnType("text")
                        .HasColumnName("citizenname");

                    b.Property<string>("CitizenPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizenphone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isblocked");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmessageat");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("unreadcount");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("CitizenConversationId");

                    b.HasIndex("TenantId", "CitizenPhone")
                        .IsUnique()
                        .HasDatabaseName("ix_citizenconversations_tenant_phone_unique");

                    b.HasIndex("TenantId", "LastMessageAt");

                    b.ToTable("citizenconversations", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("DepartmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departmenttype");

                    b.Property<Guid?>("DeputyManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deputymanageruserid");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manageruserid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentdepartmentid");

                    b.Property<string>("ResponsibleUserIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibleuseridsjson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("TenantId", "DeputyManagerUserId");

                    b.HasIndex("TenantId", "ManagerUserId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("6d146a0d-611c-48a5-b59e-8c14a22f6a2e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Administration",
                            ManagerUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            Name = "Sistem Yönetimi",
                            ResponsibleUserIdsJson = "[]",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Müdürlük",
                            ManagerUserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            Name = "Fen İşleri Müdürlüğü",
                            ResponsibleUserIdsJson = "[]",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            DepartmentId = new Guid("8f7264ff-c1df-48eb-bf39-a6ff42d7e9bc"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Müdürlük",
                            Name = "Basın Yayın Müdürlüğü",
                            ResponsibleUserIdsJson = "[]",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.EDevletActivityType", b =>
                {
                    b.Property<Guid>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activitytypeid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("ActivityTypeId");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.ToTable("edevletactivitytypes", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.EDevletDailyActivityPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("planid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activitytypeid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("OpenAddress")
                        .HasColumnType("text")
                        .HasColumnName("openaddress");

                    b.Property<int?>("PlanNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plannumber");

                    b.Property<int?>("PlanNumberYear")
                        .HasColumnType("integer")
                        .HasColumnName("plannumberyear");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("PlanId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.ToTable("edevletdailyactivityplans", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jobid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancelreason");

                    b.Property<string>("CitizenName")
                        .HasColumnType("text")
                        .HasColumnName("citizenname");

                    b.Property<string>("CitizenPhone")
                        .HasColumnType("text")
                        .HasColumnName("citizenphone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedatutc");

                    b.Property<int?>("CompletionPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("completionpercentage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duedateutc");

                    b.Property<bool>("IsCoordinated")
                        .HasColumnType("boolean")
                        .HasColumnName("iscoordinated");

                    b.Property<bool>("IsProject")
                        .HasColumnType("boolean")
                        .HasColumnName("isproject");

                    b.Property<int?>("JobNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jobnumber");

                    b.Property<int?>("JobNumberYear")
                        .HasColumnType("integer")
                        .HasColumnName("jobnumberyear");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("ManagerNote")
                        .HasColumnType("text")
                        .HasColumnName("managernote");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("OpenAddress")
                        .HasColumnType("text")
                        .HasColumnName("openaddress");

                    b.Property<Guid>("OwnerDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ownerdepartmentid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requesttype");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourcerefid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sourcetype");

                    b.Property<DateTimeOffset?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdateutc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("JobId");

                    b.HasIndex("OwnerDepartmentId");

                    b.HasIndex("TenantId", "DueDateUtc");

                    b.HasIndex("TenantId", "OwnerDepartmentId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("jobs", (string)null);

                    b.HasData(
                        new
                        {
                            JobId = new Guid("9a5b3f2e-6c1a-4b0d-8e7f-2d3c4b5a6987"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            Description = "İlk kurulum sonrası arayüz kontrolü için eklenen örnek iş.",
                            DueDateUtc = new DateTimeOffset(new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCoordinated = false,
                            IsProject = false,
                            OwnerDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            Priority = "Normal",
                            RequestType = "InternalUnit",
                            SourceType = "Manual",
                            Status = "Active",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            Title = "Örnek altyapı inceleme işi"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.JobDepartment", b =>
                {
                    b.Property<Guid>("JobDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jobdepartmentid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approvalstatus");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approvedbyuserid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decidedatutc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("rejectreason");

                    b.Property<DateTimeOffset?>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedatutc");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requestedbyuserid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("JobDepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId", "JobId");

                    b.HasIndex("TenantId", "DepartmentId", "ApprovalStatus");

                    b.ToTable("jobdepartments", (string)null);

                    b.HasData(
                        new
                        {
                            JobDepartmentId = new Guid("7c2d4e1f-5b8a-4d3c-9e6f-1a2b3c4d5e62"),
                            ApprovalStatus = "Approved",
                            ApprovedByUserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DecidedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            JobId = new Guid("9a5b3f2e-6c1a-4b0d-8e7f-2d3c4b5a6987"),
                            RequestedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RequestedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            Role = "Owner",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationid");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text")
                        .HasColumnName("actionurl");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deliverystatus");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentatutc");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationId");

                    b.HasIndex("TenantId", "TaskId");

                    b.HasIndex("TenantId", "UserId", "DeliveryStatus");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.NotificationAuditRead", b =>
                {
                    b.Property<Guid>("NotificationAuditReadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationauditreadid");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("auditlogid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationAuditReadId");

                    b.HasIndex("TenantId", "UserId", "AuditLogId")
                        .IsUnique()
                        .HasDatabaseName("ix_notificationauditreads_tenant_user_audit_unique");

                    b.ToTable("notificationauditreads", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.NotificationReadCursor", b =>
                {
                    b.Property<Guid>("NotificationReadCursorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationreadcursorid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<DateTimeOffset>("ReadThroughUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("readthroughutc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationReadCursorId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notificationreadcursors_tenant_user_unique");

                    b.ToTable("notificationreadcursors", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("PushSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pushsubscriptionid");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authkey");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dhkey");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("useragent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("PushSubscriptionId");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_pushsubscriptions_endpoint_unique");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("pushsubscriptions", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.RoutingRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ruleid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rulename");

                    b.Property<Guid>("TargetDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("targetdepartmentid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("RuleId");

                    b.HasIndex("TenantId", "RuleName");

                    b.HasIndex("TenantId", "IsActive", "Priority");

                    b.ToTable("routingrules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = new Guid("d306cbf0-88ad-48b7-9b16-14bb87e77f5f"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Keywords = "altyapı,çukur,yol,asfalt",
                            Priority = 90,
                            RuleName = "Altyapı Talepleri",
                            TargetDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialConversationEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entryid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalEntryId")
                        .HasColumnType("text")
                        .HasColumnName("externalentryid");

                    b.Property<string>("MediaId")
                        .HasColumnType("text")
                        .HasColumnName("mediaid");

                    b.Property<string>("MediaMimeType")
                        .HasColumnType("text")
                        .HasColumnName("mediamimetype");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentat");

                    b.Property<Guid>("SocialMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("socialmessageid");

                    b.HasKey("EntryId");

                    b.HasIndex("ExternalEntryId")
                        .HasFilter("externalentryid IS NOT NULL");

                    b.HasIndex("SocialMessageId");

                    b.ToTable("socialconversationentries", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialMessage", b =>
                {
                    b.Property<Guid>("SocialMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("socialmessageid");

                    b.Property<Guid?>("AssignedDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneddepartmentid");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid?>("CitizenConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("citizenconversationid");

                    b.Property<string>("CitizenHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizenhandle");

                    b.Property<int?>("CitizenRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("citizenrequestnumber");

                    b.Property<int?>("CitizenRequestNumberYear")
                        .HasColumnType("integer")
                        .HasColumnName("citizenrequestnumberyear");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("externalmessageid");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedatutc");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondedatutc");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text")
                        .HasColumnName("responsecontent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("SocialMessageId");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("CitizenConversationId");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId", "Channel", "ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_socialmessages_tenant_channel_external_unique");

                    b.HasIndex("TenantId", "Status", "ReceivedAtUtc");

                    b.ToTable("socialmessages", (string)null);

                    b.HasData(
                        new
                        {
                            SocialMessageId = new Guid("8e90888d-dc75-4264-a78b-f0a7abc9a9ab"),
                            AssignedDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            Category = "Altyapı",
                            Channel = "Instagram",
                            CitizenHandle = "tire.vatandas",
                            Content = "Yolda çukur var, ekip yönlendirebilir misiniz?",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            ExternalMessageId = "demo-instagram-message-1",
                            ReceivedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 18, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Routed",
                            Tags = "",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deploymentmode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipalityname");

                    b.Property<string>("Theme")
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.HasKey("TenantId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_domain_unique")
                        .HasFilter("domain IS NOT NULL");

                    b.HasIndex("MunicipalityName");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeploymentMode = "DedicatedHosted",
                            DisplayName = "Tire Belediyesi",
                            IsActive = true,
                            MunicipalityName = "Tire Belediyesi"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.TenantSetting", b =>
                {
                    b.Property<Guid>("TenantSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantsettingid");

                    b.Property<string>("AppearanceJson")
                        .HasColumnType("text")
                        .HasColumnName("appearancejson");

                    b.Property<string>("AuthPolicyJson")
                        .HasColumnType("text")
                        .HasColumnName("authpolicyjson");

                    b.Property<bool>("AutoRoutingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("autoroutingenabled");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<int>("DefaultSlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("defaultslahours");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("FileStorageSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("filestoragesettingsjson");

                    b.Property<string>("LdapSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("ldapsettingsjson");

                    b.Property<string>("RolePageAccessJson")
                        .HasColumnType("text")
                        .HasColumnName("rolepageaccessjson");

                    b.Property<string>("SlaWeekendSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("slaweekendsettingsjson");

                    b.Property<string>("SmsSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("smssettingsjson");

                    b.Property<string>("SocialSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("socialsettingsjson");

                    b.Property<string>("SyslogSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("syslogsettingsjson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Theme")
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<string>("WorkingHoursJson")
                        .HasColumnType("text")
                        .HasColumnName("workinghoursjson");

                    b.HasKey("TenantSettingId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenantsettings_tenantid_unique");

                    b.ToTable("tenantsettings", (string)null);

                    b.HasData(
                        new
                        {
                            TenantSettingId = new Guid("3f3efab4-c18c-4dd2-a227-c28af61d4fd5"),
                            AppearanceJson = "{\"themePreset\":\"tire-civic\",\"primaryColor\":\"#0F4C81\",\"secondaryColor\":\"#2B6EA6\",\"accentColor\":\"#C6932D\",\"neutralColor\":\"#6A7786\",\"surfaceColor\":\"#FFFFFF\",\"backgroundColor\":\"#EEF3F8\",\"headerGradientFrom\":\"#123B63\",\"headerGradientTo\":\"#356F99\",\"sidebarBackgroundColor\":\"#102F4A\",\"sidebarForegroundColor\":\"#F6F8FB\"}",
                            AuthPolicyJson = "{\"automaticSignInEnabled\":true,\"automaticSignInMode\":\"TrustedHeader\",\"trustedNetworkCidrs\":[\"127.0.0.1/32\",\"::1/128\",\"10.0.0.0/8\",\"172.16.0.0/12\",\"192.168.0.0/16\"],\"trustedProxyCidrs\":[\"127.0.0.1/32\",\"::1/128\",\"10.0.0.0/8\",\"172.16.0.0/12\",\"192.168.0.0/16\"],\"identityHeaderName\":\"X-Authenticated-User\",\"requireSecondFactorOutsideTrustedNetwork\":true,\"secondFactorProvider\":\"Mock\",\"codeLength\":6,\"codeTtlSeconds\":300,\"allowMockCodePreview\":true}",
                            AutoRoutingEnabled = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DefaultSlaHours = 48,
                            DisplayName = "Tire Belediyesi",
                            LdapSettingsJson = "{\"enabled\":true,\"domain\":\"tire.bel.tr\",\"userAttribute\":\"mail\"}",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.UserDepartmentAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("isprimary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "DepartmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_userdeptassign_tenantid_userid_deptid_unique");

                    b.ToTable("userdepartmentassignments", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WhatsAppMessageTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("templateid");

                    b.Property<string>("ActiveDaysJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activedaysjson");

                    b.Property<bool>("AutoReply")
                        .HasColumnType("boolean")
                        .HasColumnName("autoreply");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<bool>("HasKeyword")
                        .HasColumnType("boolean")
                        .HasColumnName("haskeyword");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("boolean")
                        .HasColumnName("isgeneral");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywordsjson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("querytype");

                    b.Property<int>("ReplyDelaySecs")
                        .HasColumnType("integer")
                        .HasColumnName("replydelaysecs");

                    b.Property<bool>("TimedReplyEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("timedreplyenabled");

                    b.Property<string>("TimedReplyEndTime")
                        .HasColumnType("text")
                        .HasColumnName("timedreplyendtime");

                    b.Property<string>("TimedReplyStartTime")
                        .HasColumnType("text")
                        .HasColumnName("timedreplystarttime");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("TemplateId");

                    b.HasIndex("TenantId", "Channel", "IsActive");

                    b.ToTable("whatsapptemplates", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("actualhours");

                    b.Property<DateTimeOffset?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignedatutc");

                    b.Property<Guid?>("AssignedDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneddepartmentid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneduserid");

                    b.Property<Guid?>("AssigningManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigningmanagerid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedatutc");

                    b.Property<int?>("CompletionPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("completionpercentage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currentstatus");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duedateutc");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("estimatedhours");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owneruserid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RevisionReason")
                        .HasColumnType("text")
                        .HasColumnName("revisionreason");

                    b.Property<DateTimeOffset?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdateutc");

                    b.Property<int?>("TaskNumber")
                        .HasColumnType("integer")
                        .HasColumnName("tasknumber");

                    b.Property<int?>("TaskNumberYear")
                        .HasColumnType("integer")
                        .HasColumnName("tasknumberyear");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("TaskId");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId", "AssignedDepartmentId");

                    b.HasIndex("TenantId", "AssignedUserId");

                    b.HasIndex("TenantId", "CurrentStatus");

                    b.HasIndex("TenantId", "DueDateUtc");

                    b.HasIndex("TenantId", "JobId");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("6de6e0b3-a74e-4f24-bdbc-4d6e0cb6d38c"),
                            AssignedDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            AssignedUserId = new Guid("1358d4aa-b1ae-486c-a1db-a757ea18f2c3"),
                            AssigningManagerId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            CurrentStatus = "Assigned",
                            Description = "İlk kurulum sonrası arayüz kontrolü için eklenen örnek görev.",
                            DueDateUtc = new DateTimeOffset(new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobId = new Guid("9a5b3f2e-6c1a-4b0d-8e7f-2d3c4b5a6987"),
                            Priority = "Normal",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            Title = "Örnek altyapı inceleme görevi"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkflowApproval", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approvalid");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approveruserid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<DateTimeOffset?>("DecisionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decisiondateutc");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("steporder");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subjectid");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjecttype");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("ApprovalId");

                    b.HasIndex("TenantId", "ApproverUserId", "Decision");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId", "StepOrder");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AssignmentHistory", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.WorkTask", "Task")
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.CitizenConversation", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Departments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDepartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.EDevletDailyActivityPlan", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.EDevletActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Job", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "OwnerDepartment")
                        .WithMany()
                        .HasForeignKey("OwnerDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerDepartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.JobDepartment", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Job", "Job")
                        .WithMany("Departments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialConversationEntry", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.SocialMessage", "SocialMessage")
                        .WithMany()
                        .HasForeignKey("SocialMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialMessage");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialMessage", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "AssignedDepartment")
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.CitizenConversation", "CitizenConversation")
                        .WithMany("SocialMessages")
                        .HasForeignKey("CitizenConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SocialMessages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepartment");

                    b.Navigation("CitizenConversation");

                    b.Navigation("Job");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.UserDepartmentAssignment", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.ApplicationUser", "User")
                        .WithMany("DepartmentAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WhatsAppMessageTemplate", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tasks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("DepartmentAssignments");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.CitizenConversation", b =>
                {
                    b.Navigation("SocialMessages");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Job", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("SocialMessages");

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.Navigation("AssignmentHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
