// <auto-generated />
using System;
using CityCommunicationCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityCommunicationCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CityCommunicationCenterDbContext))]
    partial class CityCommunicationCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalIdentityId")
                        .HasColumnType("text")
                        .HasColumnName("externalidentityid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manageruserid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rolecode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<string>("UserSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usersource");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId", "Email");

                    b.HasIndex("TenantId", "RoleCode");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenantid_username_unique")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("6d146a0d-611c-48a5-b59e-8c14a22f6a2e"),
                            DisplayName = "Sistem Yöneticisi",
                            Email = "admin@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "SystemAdmin",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            DisplayName = "Zeynep Kara",
                            Email = "zeynep.kara@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "Manager",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "zeynep.kara"
                        },
                        new
                        {
                            UserId = new Guid("1358d4aa-b1ae-486c-a1db-a757ea18f2c3"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            DisplayName = "Emre Çelik",
                            Email = "emre.celik@tire.bel.tr",
                            IsActive = true,
                            ManagerUserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            RoleCode = "Staff",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "emre.celik"
                        },
                        new
                        {
                            UserId = new Guid("1e96916a-889a-4701-a0e6-71dc6571ac18"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentId = new Guid("8f7264ff-c1df-48eb-bf39-a6ff42d7e9bc"),
                            DisplayName = "Ali Yıldız",
                            Email = "ali.yildiz@tire.bel.tr",
                            IsActive = true,
                            RoleCode = "Operator",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            UserSource = "Manual",
                            Username = "ali.yildiz"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approvalid");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approveruserid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<DateTimeOffset?>("DecisionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decisiondateutc");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("steporder");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("ApprovalId");

                    b.HasIndex("TaskId", "StepOrder");

                    b.HasIndex("TenantId", "ApproverUserId");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AssignmentHistory", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<DateTimeOffset>("ActionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actiondateutc");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actiontype");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<Guid?>("FromDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fromdepartmentid");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("fromuserid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<Guid?>("ToDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("todepartmentid");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("touserid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("TaskId", "ActionDateUtc");

                    b.HasIndex("TenantId", "ToDepartmentId");

                    b.ToTable("assignmenthistory", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("auditlogid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actoruserid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entitytype");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eventtimeutc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("AuditLogId");

                    b.HasIndex("TenantId", "EventTimeUtc");

                    b.HasIndex("TenantId", "EntityType", "EntityId");

                    b.ToTable("auditlogs", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("departmentid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("DepartmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departmenttype");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manageruserid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentdepartmentid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("TenantId", "ManagerUserId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("6d146a0d-611c-48a5-b59e-8c14a22f6a2e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Administration",
                            ManagerUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            Name = "Sistem Yönetimi",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            DepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Müdürlük",
                            ManagerUserId = new Guid("d6fc7a5b-5cb2-4c59-8a82-7843041421a5"),
                            Name = "Fen İşleri Müdürlüğü",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            DepartmentId = new Guid("8f7264ff-c1df-48eb-bf39-a6ff42d7e9bc"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DepartmentType = "Müdürlük",
                            Name = "Basın Yayın Müdürlüğü",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deliverystatus");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentatutc");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationId");

                    b.HasIndex("TenantId", "TaskId");

                    b.HasIndex("TenantId", "UserId", "DeliveryStatus");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.RoutingRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ruleid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rulename");

                    b.Property<Guid>("TargetDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("targetdepartmentid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("RuleId");

                    b.HasIndex("TenantId", "RuleName");

                    b.HasIndex("TenantId", "IsActive", "Priority");

                    b.ToTable("routingrules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = new Guid("d306cbf0-88ad-48b7-9b16-14bb87e77f5f"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Keywords = "altyapı,çukur,yol,asfalt",
                            Priority = 90,
                            RuleName = "Altyapı Talepleri",
                            TargetDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialMessage", b =>
                {
                    b.Property<Guid>("SocialMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("socialmessageid");

                    b.Property<Guid?>("AssignedDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneddepartmentid");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("CitizenHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizenhandle");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("externalmessageid");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedatutc");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondedatutc");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text")
                        .HasColumnName("responsecontent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("SocialMessageId");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TenantId", "Channel", "ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_socialmessages_tenant_channel_external_unique");

                    b.HasIndex("TenantId", "Status", "ReceivedAtUtc");

                    b.ToTable("socialmessages", (string)null);

                    b.HasData(
                        new
                        {
                            SocialMessageId = new Guid("8e90888d-dc75-4264-a78b-f0a7abc9a9ab"),
                            AssignedDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            Category = "Altyapı",
                            Channel = "Instagram",
                            CitizenHandle = "tire.vatandas",
                            Content = "Yolda çukur var, ekip yönlendirebilir misiniz?",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            ExternalMessageId = "demo-instagram-message-1",
                            ReceivedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 18, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Routed",
                            Tags = "",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deploymentmode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipalityname");

                    b.Property<string>("Theme")
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.HasKey("TenantId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_domain_unique")
                        .HasFilter("domain IS NOT NULL");

                    b.HasIndex("MunicipalityName");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeploymentMode = "DedicatedHosted",
                            DisplayName = "Tire Belediyesi",
                            IsActive = true,
                            MunicipalityName = "Tire Belediyesi"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.TenantSetting", b =>
                {
                    b.Property<Guid>("TenantSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantsettingid");

                    b.Property<string>("AppearanceJson")
                        .HasColumnType("text")
                        .HasColumnName("appearancejson");

                    b.Property<string>("AuthPolicyJson")
                        .HasColumnType("text")
                        .HasColumnName("authpolicyjson");

                    b.Property<bool>("AutoRoutingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("autoroutingenabled");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<int>("DefaultSlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("defaultslahours");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("LdapSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("ldapsettingsjson");

                    b.Property<string>("SocialSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("socialsettingsjson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Theme")
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("TenantSettingId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenantsettings_tenantid_unique");

                    b.ToTable("tenantsettings", (string)null);

                    b.HasData(
                        new
                        {
                            TenantSettingId = new Guid("3f3efab4-c18c-4dd2-a227-c28af61d4fd5"),
                            AppearanceJson = "{\"themePreset\":\"tire-civic\",\"primaryColor\":\"#0F4C81\",\"secondaryColor\":\"#2B6EA6\",\"accentColor\":\"#C6932D\",\"neutralColor\":\"#6A7786\",\"surfaceColor\":\"#FFFFFF\",\"backgroundColor\":\"#EEF3F8\",\"headerGradientFrom\":\"#123B63\",\"headerGradientTo\":\"#356F99\",\"sidebarBackgroundColor\":\"#102F4A\",\"sidebarForegroundColor\":\"#F6F8FB\"}",
                            AuthPolicyJson = "{\"automaticSignInEnabled\":true,\"automaticSignInMode\":\"TrustedHeader\",\"trustedNetworkCidrs\":[\"127.0.0.1/32\",\"::1/128\",\"10.0.0.0/8\",\"172.16.0.0/12\",\"192.168.0.0/16\"],\"trustedProxyCidrs\":[\"127.0.0.1/32\",\"::1/128\",\"10.0.0.0/8\",\"172.16.0.0/12\",\"192.168.0.0/16\"],\"identityHeaderName\":\"X-Authenticated-User\",\"requireSecondFactorOutsideTrustedNetwork\":true,\"secondFactorProvider\":\"Mock\",\"codeLength\":6,\"codeTtlSeconds\":300,\"allowMockCodePreview\":true}",
                            AutoRoutingEnabled = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            DefaultSlaHours = 48,
                            DisplayName = "Tire Belediyesi",
                            LdapSettingsJson = "{\"enabled\":true,\"domain\":\"tire.bel.tr\",\"userAttribute\":\"mail\"}",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("taskid");

                    b.Property<Guid?>("AssignedDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneddepartmentid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigneduserid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closedatutc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedatutc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currentstatus");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duedateutc");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourcerefid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sourcetype");

                    b.Property<Guid?>("TargetDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("targetdepartmentid");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tasktype");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updatedbyuserid");

                    b.HasKey("TaskId");

                    b.HasIndex("TenantId", "AssignedDepartmentId");

                    b.HasIndex("TenantId", "AssignedUserId");

                    b.HasIndex("TenantId", "CurrentStatus");

                    b.HasIndex("TenantId", "DueDateUtc");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("6de6e0b3-a74e-4f24-bdbc-4d6e0cb6d38c"),
                            AssignedDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            AssignedUserId = new Guid("1358d4aa-b1ae-486c-a1db-a757ea18f2c3"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("4b1efb47-0311-4ef7-9a0c-f4c41dcb8b48"),
                            CurrentStatus = "Assigned",
                            Description = "İlk kurulum sonrası arayüz kontrolü için eklenen örnek görev.",
                            DueDateUtc = new DateTimeOffset(new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "Normal",
                            SourceType = "Manual",
                            TargetDepartmentId = new Guid("0e29fb34-64da-429e-b7c0-e6016a0c10a7"),
                            TaskType = "CitizenRequest",
                            TenantId = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            Title = "Örnek altyapı inceleme görevi"
                        });
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Approval", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.WorkTask", "Task")
                        .WithMany("Approvals")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.AssignmentHistory", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.WorkTask", "Task")
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Departments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDepartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.SocialMessage", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Department", "AssignedDepartment")
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SocialMessages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepartment");

                    b.Navigation("Task");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("CityCommunicationCenter.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tasks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("SocialMessages");

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CityCommunicationCenter.Domain.Entities.WorkTask", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssignmentHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
