/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/tenants/{tenantId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TenantSettingsResponse"];
                        "application/json": components["schemas"]["TenantSettingsResponse"];
                        "text/json": components["schemas"]["TenantSettingsResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTenantSettingsRequest"];
                    "text/json": components["schemas"]["UpdateTenantSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateTenantSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PublishWorkflowRequest"];
                    "text/json": components["schemas"]["PublishWorkflowRequest"];
                    "application/*+json": components["schemas"]["PublishWorkflowRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditLogResponse"][];
                        "application/json": components["schemas"]["AuditLogResponse"][];
                        "text/json": components["schemas"]["AuditLogResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponse"][];
                        "application/json": components["schemas"]["DepartmentResponse"][];
                        "text/json": components["schemas"]["DepartmentResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDepartmentRequest"];
                    "text/json": components["schemas"]["CreateDepartmentRequest"];
                    "application/*+json": components["schemas"]["CreateDepartmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponse"];
                        "application/json": components["schemas"]["DepartmentResponse"];
                        "text/json": components["schemas"]["DepartmentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserResponse"];
                        "application/json": components["schemas"]["CurrentUserResponse"];
                        "text/json": components["schemas"]["CurrentUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NotificationResponse"][];
                        "application/json": components["schemas"]["NotificationResponse"][];
                        "text/json": components["schemas"]["NotificationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TestNotificationRequest"];
                    "text/json": components["schemas"]["TestNotificationRequest"];
                    "application/*+json": components["schemas"]["TestNotificationRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateNotificationPreferencesRequest"];
                    "text/json": components["schemas"]["UpdateNotificationPreferencesRequest"];
                    "application/*+json": components["schemas"]["UpdateNotificationPreferencesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponse"];
                        "application/json": components["schemas"]["DashboardResponse"];
                        "text/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlaReportResponse"];
                        "application/json": components["schemas"]["SlaReportResponse"];
                        "text/json": components["schemas"]["SlaReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/workload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkloadReportItemResponse"][];
                        "application/json": components["schemas"]["WorkloadReportItemResponse"][];
                        "text/json": components["schemas"]["WorkloadReportItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/social-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SocialTrendReportItemResponse"][];
                        "application/json": components["schemas"]["SocialTrendReportItemResponse"][];
                        "text/json": components["schemas"]["SocialTrendReportItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoutingConfigResponse"];
                        "application/json": components["schemas"]["RoutingConfigResponse"];
                        "text/json": components["schemas"]["RoutingConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/routing/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ToggleAutoRoutingRequest"];
                    "text/json": components["schemas"]["ToggleAutoRoutingRequest"];
                    "application/*+json": components["schemas"]["ToggleAutoRoutingRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/routing/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRoutingRuleRequest"];
                    "text/json": components["schemas"]["CreateRoutingRuleRequest"];
                    "application/*+json": components["schemas"]["CreateRoutingRuleRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoutingRuleResponse"];
                        "application/json": components["schemas"]["RoutingRuleResponse"];
                        "text/json": components["schemas"]["RoutingRuleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/routing/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRoutingRuleRequest"];
                    "text/json": components["schemas"]["UpdateRoutingRuleRequest"];
                    "application/*+json": components["schemas"]["UpdateRoutingRuleRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/routing/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RoutingTestRequest"];
                    "text/json": components["schemas"]["RoutingTestRequest"];
                    "application/*+json": components["schemas"]["RoutingTestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoutingTestResponse"];
                        "application/json": components["schemas"]["RoutingTestResponse"];
                        "text/json": components["schemas"]["RoutingTestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SocialMessageSummaryResponse"][];
                        "application/json": components["schemas"]["SocialMessageSummaryResponse"][];
                        "text/json": components["schemas"]["SocialMessageSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SocialMessageDetailResponse"];
                        "application/json": components["schemas"]["SocialMessageDetailResponse"];
                        "text/json": components["schemas"]["SocialMessageDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/messages/{messageId}/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategorizeSocialMessageRequest"];
                    "text/json": components["schemas"]["CategorizeSocialMessageRequest"];
                    "application/*+json": components["schemas"]["CategorizeSocialMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/messages/{messageId}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RouteSocialMessageRequest"];
                    "text/json": components["schemas"]["RouteSocialMessageRequest"];
                    "application/*+json": components["schemas"]["RouteSocialMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/messages/{messageId}/convert-to-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConvertSocialMessageToTaskRequest"];
                    "text/json": components["schemas"]["ConvertSocialMessageToTaskRequest"];
                    "application/*+json": components["schemas"]["ConvertSocialMessageToTaskRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskSummaryResponse"];
                        "application/json": components["schemas"]["TaskSummaryResponse"];
                        "text/json": components["schemas"]["TaskSummaryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/x": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["XSettingsRequest"];
                    "text/json": components["schemas"]["XSettingsRequest"];
                    "application/*+json": components["schemas"]["XSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FacebookSettingsRequest"];
                    "text/json": components["schemas"]["FacebookSettingsRequest"];
                    "application/*+json": components["schemas"]["FacebookSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InstagramSettingsRequest"];
                    "text/json": components["schemas"]["InstagramSettingsRequest"];
                    "application/*+json": components["schemas"]["InstagramSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WhatsAppSettingsRequest"];
                    "text/json": components["schemas"]["WhatsAppSettingsRequest"];
                    "application/*+json": components["schemas"]["WhatsAppSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/{channel}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    channel: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/social-settings/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    channel: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/webhooks/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    channel: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SocialWebhookRequest"];
                    "text/json": components["schemas"]["SocialWebhookRequest"];
                    "application/*+json": components["schemas"]["SocialWebhookRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskSummaryResponse"][];
                        "application/json": components["schemas"]["TaskSummaryResponse"][];
                        "text/json": components["schemas"]["TaskSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                    "text/json": components["schemas"]["CreateTaskRequest"];
                    "application/*+json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskSummaryResponse"];
                        "application/json": components["schemas"]["TaskSummaryResponse"];
                        "text/json": components["schemas"]["TaskSummaryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitTaskRequest"];
                    "text/json": components["schemas"]["SubmitTaskRequest"];
                    "application/*+json": components["schemas"]["SubmitTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApprovalActionRequest"];
                    "text/json": components["schemas"]["ApprovalActionRequest"];
                    "application/*+json": components["schemas"]["ApprovalActionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApprovalActionRequest"];
                    "text/json": components["schemas"]["ApprovalActionRequest"];
                    "application/*+json": components["schemas"]["ApprovalActionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AssignTaskRequest"];
                    "text/json": components["schemas"]["AssignTaskRequest"];
                    "application/*+json": components["schemas"]["AssignTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteTaskRequest"];
                    "text/json": components["schemas"]["CompleteTaskRequest"];
                    "application/*+json": components["schemas"]["CompleteTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CloseTaskRequest"];
                    "text/json": components["schemas"]["CloseTaskRequest"];
                    "application/*+json": components["schemas"]["CloseTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSummaryResponse"][];
                        "application/json": components["schemas"]["UserSummaryResponse"][];
                        "text/json": components["schemas"]["UserSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/sync/ad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: {
                    "x-api-version"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApprovalActionRequest: {
            comment?: string | null;
        };
        ApprovalStepResponse: {
            /** Format: uuid */
            approvalId?: string;
            /** Format: uuid */
            approverUserId?: string;
            /** Format: int32 */
            stepOrder?: number;
            decision?: string | null;
            /** Format: date-time */
            decisionDateUtc?: string | null;
            comment?: string | null;
        };
        AssignTaskRequest: {
            /** Format: uuid */
            departmentId?: string | null;
            /** Format: uuid */
            userId?: string | null;
            actionType?: string | null;
        };
        AssignmentHistoryResponse: {
            /** Format: uuid */
            assignmentId?: string;
            /** Format: uuid */
            fromDepartmentId?: string | null;
            /** Format: uuid */
            toDepartmentId?: string | null;
            /** Format: uuid */
            fromUserId?: string | null;
            /** Format: uuid */
            toUserId?: string | null;
            actionType?: string | null;
            /** Format: date-time */
            actionDateUtc?: string;
        };
        AuditLogResponse: {
            /** Format: uuid */
            auditLogId?: string;
            /** Format: uuid */
            tenantId?: string;
            entityType?: string | null;
            entityId?: string | null;
            action?: string | null;
            /** Format: uuid */
            actorUserId?: string | null;
            /** Format: date-time */
            eventTimeUtc?: string;
            details?: string | null;
        };
        CategorizeSocialMessageRequest: {
            category?: string | null;
            tags?: string[] | null;
        };
        CloseTaskRequest: {
            closureNote?: string | null;
        };
        CompleteTaskRequest: {
            resultNote?: string | null;
        };
        ConvertSocialMessageToTaskRequest: {
            title?: string | null;
            description?: string | null;
            priority?: string | null;
            /** Format: date-time */
            dueDateUtc?: string | null;
        };
        CreateDepartmentRequest: {
            name?: string | null;
            departmentType?: string | null;
            /** Format: uuid */
            parentDepartmentId?: string | null;
            /** Format: uuid */
            managerUserId?: string | null;
        };
        CreateRoutingRuleRequest: {
            ruleName?: string | null;
            keywords?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string;
            /** Format: int32 */
            priority?: number;
        };
        CreateTaskRequest: {
            title?: string | null;
            description?: string | null;
            taskType?: string | null;
            sourceType?: string | null;
            /** Format: uuid */
            sourceRefId?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string | null;
            priority?: string | null;
            /** Format: date-time */
            dueDateUtc?: string | null;
        };
        CurrentUserResponse: {
            /** Format: uuid */
            tenantId?: string | null;
            /** Format: uuid */
            userId?: string | null;
            displayName?: string | null;
            roleCode?: string | null;
            isAuthenticated?: boolean;
            resolutionSource?: string | null;
        };
        DashboardResponse: {
            /** Format: int32 */
            openTaskCount?: number;
            /** Format: int32 */
            pendingApprovalCount?: number;
            /** Format: int32 */
            activeSocialMessageCount?: number;
            /** Format: int32 */
            failedNotificationCount?: number;
        };
        DepartmentResponse: {
            /** Format: uuid */
            departmentId?: string;
            /** Format: uuid */
            tenantId?: string;
            name?: string | null;
            departmentType?: string | null;
            /** Format: uuid */
            parentDepartmentId?: string | null;
            /** Format: uuid */
            managerUserId?: string | null;
        };
        FacebookSettingsRequest: {
            appId?: string | null;
            appSecret?: string | null;
            pageAccessToken?: string | null;
            pageId?: string | null;
            webhookVerifyToken?: string | null;
        };
        InstagramSettingsRequest: {
            accountId?: string | null;
            accessToken?: string | null;
            linkedPageId?: string | null;
        };
        LoginRequest: {
            username?: string | null;
            password?: string | null;
            tenantId?: string | null;
        };
        NotificationResponse: {
            /** Format: uuid */
            notificationId?: string;
            /** Format: uuid */
            taskId?: string | null;
            /** Format: uuid */
            userId?: string;
            channel?: string | null;
            deliveryStatus?: string | null;
            message?: string | null;
            /** Format: date-time */
            sentAtUtc?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        PublishWorkflowRequest: {
            workflowName?: string | null;
            /** Format: int32 */
            version?: number;
            description?: string | null;
        };
        RouteSocialMessageRequest: {
            /** Format: uuid */
            departmentId?: string | null;
            /** Format: uuid */
            userId?: string | null;
        };
        RoutingConfigResponse: {
            autoRoutingEnabled?: boolean;
            rules?: components["schemas"]["RoutingRuleResponse"][] | null;
        };
        RoutingRuleResponse: {
            /** Format: uuid */
            ruleId?: string;
            ruleName?: string | null;
            keywords?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string;
            targetDepartmentName?: string | null;
            /** Format: int32 */
            priority?: number;
            isActive?: boolean;
        };
        RoutingTestRequest: {
            messageContent?: string | null;
        };
        RoutingTestResponse: {
            /** Format: uuid */
            targetDepartmentId?: string | null;
            targetDepartmentName?: string | null;
        };
        SlaReportResponse: {
            /** Format: int32 */
            overdueTaskCount?: number;
            /** Format: int32 */
            dueTodayTaskCount?: number;
        };
        SocialMessageDetailResponse: {
            /** Format: uuid */
            socialMessageId?: string;
            /** Format: uuid */
            tenantId?: string;
            channel?: string | null;
            externalMessageId?: string | null;
            citizenHandle?: string | null;
            content?: string | null;
            category?: string | null;
            status?: string | null;
            /** Format: uuid */
            assignedDepartmentId?: string | null;
            /** Format: uuid */
            taskId?: string | null;
            /** Format: date-time */
            receivedAtUtc?: string;
            tags?: string[] | null;
        };
        SocialMessageSummaryResponse: {
            /** Format: uuid */
            socialMessageId?: string;
            channel?: string | null;
            citizenHandle?: string | null;
            category?: string | null;
            status?: string | null;
            /** Format: uuid */
            assignedDepartmentId?: string | null;
            /** Format: uuid */
            taskId?: string | null;
            /** Format: date-time */
            receivedAtUtc?: string;
        };
        SocialTrendReportItemResponse: {
            channel?: string | null;
            /** Format: int32 */
            messageCount?: number;
        };
        SocialWebhookRequest: {
            externalMessageId?: string | null;
            citizenHandle?: string | null;
            content?: string | null;
            channel?: string | null;
            /** Format: date-time */
            receivedAtUtc?: string | null;
        };
        SubmitTaskRequest: {
            note?: string | null;
        };
        TaskDetailResponse: {
            /** Format: uuid */
            taskId?: string;
            /** Format: uuid */
            tenantId?: string;
            title?: string | null;
            description?: string | null;
            taskType?: string | null;
            sourceType?: string | null;
            priority?: string | null;
            currentStatus?: string | null;
            /** Format: uuid */
            sourceRefId?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string | null;
            /** Format: uuid */
            assignedDepartmentId?: string | null;
            /** Format: uuid */
            assignedUserId?: string | null;
            /** Format: date-time */
            dueDateUtc?: string | null;
            approvals?: components["schemas"]["ApprovalStepResponse"][] | null;
            assignmentHistory?: components["schemas"]["AssignmentHistoryResponse"][] | null;
        };
        TaskSummaryResponse: {
            /** Format: uuid */
            taskId?: string;
            /** Format: uuid */
            tenantId?: string;
            title?: string | null;
            taskType?: string | null;
            priority?: string | null;
            currentStatus?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string | null;
            /** Format: uuid */
            assignedUserId?: string | null;
            /** Format: date-time */
            dueDateUtc?: string | null;
        };
        TenantSettingsResponse: {
            /** Format: uuid */
            tenantId?: string;
            displayName?: string | null;
            theme?: string | null;
            domain?: string | null;
            /** Format: int32 */
            defaultSlaHours?: number;
        };
        TestNotificationRequest: {
            channel?: string | null;
            recipient?: string | null;
            message?: string | null;
        };
        ToggleAutoRoutingRequest: {
            enabled?: boolean;
        };
        UpdateNotificationPreferencesRequest: {
            emailEnabled?: boolean;
            smsEnabled?: boolean;
            inAppEnabled?: boolean;
        };
        UpdateRoutingRuleRequest: {
            ruleName?: string | null;
            keywords?: string | null;
            /** Format: uuid */
            targetDepartmentId?: string;
            /** Format: int32 */
            priority?: number;
            isActive?: boolean;
        };
        UpdateTenantSettingsRequest: {
            displayName?: string | null;
            theme?: string | null;
            domain?: string | null;
            /** Format: int32 */
            defaultSlaHours?: number;
        };
        UserSummaryResponse: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            departmentId?: string;
            displayName?: string | null;
            email?: string | null;
            roleCode?: string | null;
            isActive?: boolean;
        };
        WhatsAppSettingsRequest: {
            businessAccountId?: string | null;
            phoneNumberId?: string | null;
            accessToken?: string | null;
            webhookVerifyToken?: string | null;
        };
        WorkloadReportItemResponse: {
            /** Format: uuid */
            departmentId?: string;
            /** Format: int32 */
            openTaskCount?: number;
        };
        XSettingsRequest: {
            apiKey?: string | null;
            apiSecret?: string | null;
            accessToken?: string | null;
            accessTokenSecret?: string | null;
            bearerToken?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetById: {
        parameters: {
            query?: {
                "api-version"?: string;
            };
            header?: {
                "x-api-version"?: string;
            };
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["TaskDetailResponse"];
                    "application/json": components["schemas"]["TaskDetailResponse"];
                    "text/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
