namespace CityCommunicationCenter.Application.Common;

/// <summary>
/// Tire ilçesi mahalle kataloğu — frontend <c>izmir-locations.ts</c> ile senkron tutulur.
/// Dashboard mahalle pie chart'larında 0 sayılı dilimler için kullanılır (R548).
/// </summary>
public static class TireNeighborhoodCatalog
{
    public static IReadOnlyList<string> Names { get; } =
    [
        "4 Eylül",
        "Adnan Menderes",
        "Akçaşehir",
        "Akkoyunlu",
        "Akmescit",
        "Akyurt",
        "Alacalı",
        "Alaylı",
        "Armutlu",
        "Atatürk",
        "Ayaklıkırı",
        "Bahariye",
        "Başköy",
        "Boynuyoğun",
        "Büyükkale",
        "Büyükkemerdere",
        "Büyükkömürcü",
        "Cambazlı",
        "Cumhuriyet",
        "Çayırlı",
        "Çeriközü",
        "Çiniyeri",
        "Çobanköy",
        "Çukurköy",
        "Dağdere",
        "Dallık",
        "Dere",
        "Derebaşı",
        "Dereli",
        "Dibekçi",
        "Doyranlı",
        "Duatepe",
        "Dumlupınar",
        "Dündarlı",
        "Eğridere",
        "Ertuğrul",
        "Eskioba",
        "Fatih",
        "Gökçen",
        "Halkapınar",
        "Hasançavuşlar",
        "Hisarlık",
        "Hürriyet",
        "Işıklar",
        "Işıklı",
        "İbni Melek",
        "İbnimelek OSB",
        "İhsaniye",
        "İpekçiler",
        "İstiklal",
        "Kahrat",
        "Kaplan",
        "Karaca Ali",
        "Karateke",
        "Ketenci",
        "Kırtepe",
        "Kızılcahavlu",
        "Kireli",
        "Kocaaliler",
        "Kurşak",
        "Kurtuluş",
        "Küçükburun",
        "Küçükkale",
        "Küçükkemerdere",
        "Küçükkömürcü",
        "Kürdüllü",
        "Mahmutlar",
        "Mehmetler",
        "Musalar",
        "Ortaköy",
        "Osmancık",
        "Paşa",
        "Peşrefli",
        "Sarılar",
        "Saruhanlı",
        "Somak",
        "TOKİ",
        "Topalak",
        "Toparlar",
        "Turan",
        "Turgutlu",
        "Üzümler",
        "Yamandere",
        "Yeğenli",
        "Yemişler",
        "Yeni",
        "Yeniçiftlik",
        "Yenioba",
        "Yenişehir",
    ];
}
